// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomMessage.proto

package fun.codenow.netty.message;

public final class CustomMessageProto {
  private CustomMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CustomMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.CustomMessage.CustomHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <code>.CustomMessage.CustomHeader header = 1;</code>
     * @return The header.
     */
    CustomMessage.CustomHeader getHeader();
    /**
     * <code>.CustomMessage.CustomHeader header = 1;</code>
     */
    CustomMessage.CustomHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>.google.protobuf.Any body = 2;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <code>.google.protobuf.Any body = 2;</code>
     * @return The body.
     */
    com.google.protobuf.Any getBody();
    /**
     * <code>.google.protobuf.Any body = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
  }
  /**
   * Protobuf type {@code CustomMessage}
   */
  public static final class CustomMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CustomMessage)
      CustomMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CustomMessage.newBuilder() to construct.
    private CustomMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CustomMessage() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CustomMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CustomMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              CustomHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(CustomHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (body_ != null) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CustomMessageProto.internal_static_CustomMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CustomMessageProto.internal_static_CustomMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CustomMessage.class, Builder.class);
    }

    public interface CustomHeaderOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CustomMessage.CustomHeader)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int32 crcCode = 1;</code>
       * @return The crcCode.
       */
      int getCrcCode();

      /**
       * <code>int32 length = 2;</code>
       * @return The length.
       */
      int getLength();

      /**
       * <code>int64 sessionId = 3;</code>
       * @return The sessionId.
       */
      long getSessionId();

      /**
       * <code>.CustomMessage.CustomHeader.MessgeType type = 4;</code>
       * @return The enum numeric value on the wire for type.
       */
      int getTypeValue();
      /**
       * <code>.CustomMessage.CustomHeader.MessgeType type = 4;</code>
       * @return The type.
       */
      CustomHeader.MessgeType getType();

      /**
       * <code>int32 priority = 5;</code>
       * @return The priority.
       */
      int getPriority();

      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */
      int getAttachmentCount();
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */
      boolean containsAttachment(
              String key);
      /**
       * Use {@link #getAttachmentMap()} instead.
       */
      @Deprecated
      java.util.Map<String, com.google.protobuf.Any>
      getAttachment();
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */
      java.util.Map<String, com.google.protobuf.Any>
      getAttachmentMap();
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */

      com.google.protobuf.Any getAttachmentOrDefault(
              String key,
              com.google.protobuf.Any defaultValue);
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */

      com.google.protobuf.Any getAttachmentOrThrow(
              String key);
    }
    /**
     * Protobuf type {@code CustomMessage.CustomHeader}
     */
    public static final class CustomHeader extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:CustomMessage.CustomHeader)
        CustomHeaderOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use CustomHeader.newBuilder() to construct.
      private CustomHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private CustomHeader() {
        type_ = 0;
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new CustomHeader();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private CustomHeader(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                crcCode_ = input.readInt32();
                break;
              }
              case 16: {

                length_ = input.readInt32();
                break;
              }
              case 24: {

                sessionId_ = input.readInt64();
                break;
              }
              case 32: {
                int rawValue = input.readEnum();

                type_ = rawValue;
                break;
              }
              case 40: {

                priority_ = input.readInt32();
                break;
              }
              case 50: {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  attachment_ = com.google.protobuf.MapField.newMapField(
                      AttachmentDefaultEntryHolder.defaultEntry);
                  mutable_bitField0_ |= 0x00000001;
                }
                com.google.protobuf.MapEntry<String, com.google.protobuf.Any>
                attachment__ = input.readMessage(
                    AttachmentDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                attachment_.getMutableMap().put(
                    attachment__.getKey(), attachment__.getValue());
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomMessageProto.internal_static_CustomMessage_CustomHeader_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      @Override
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetAttachment();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomMessageProto.internal_static_CustomMessage_CustomHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CustomHeader.class, Builder.class);
      }

      /**
       * Protobuf enum {@code CustomMessage.CustomHeader.MessgeType}
       */
      public enum MessgeType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <pre>
         *业务请求消息
         * </pre>
         *
         * <code>SERVICE_REQ = 0;</code>
         */
        SERVICE_REQ(0),
        /**
         * <pre>
         *业务响应消息
         * </pre>
         *
         * <code>SERVICE_RESP = 1;</code>
         */
        SERVICE_RESP(1),
        /**
         * <pre>
         *业务ONE WAY消息（既是请求又是响应消息)
         * </pre>
         *
         * <code>ONE_WAY = 2;</code>
         */
        ONE_WAY(2),
        /**
         * <pre>
         *握手请求消息
         * </pre>
         *
         * <code>LOGIN_REQ = 3;</code>
         */
        LOGIN_REQ(3),
        /**
         * <pre>
         *握手响应消息
         * </pre>
         *
         * <code>LOGIN_RESP = 4;</code>
         */
        LOGIN_RESP(4),
        /**
         * <pre>
         *心跳请求消息
         * </pre>
         *
         * <code>PING = 5;</code>
         */
        PING(5),
        /**
         * <pre>
         *心跳响应消息
         * </pre>
         *
         * <code>PONG = 6;</code>
         */
        PONG(6),
        UNRECOGNIZED(-1),
        ;

        /**
         * <pre>
         *业务请求消息
         * </pre>
         *
         * <code>SERVICE_REQ = 0;</code>
         */
        public static final int SERVICE_REQ_VALUE = 0;
        /**
         * <pre>
         *业务响应消息
         * </pre>
         *
         * <code>SERVICE_RESP = 1;</code>
         */
        public static final int SERVICE_RESP_VALUE = 1;
        /**
         * <pre>
         *业务ONE WAY消息（既是请求又是响应消息)
         * </pre>
         *
         * <code>ONE_WAY = 2;</code>
         */
        public static final int ONE_WAY_VALUE = 2;
        /**
         * <pre>
         *握手请求消息
         * </pre>
         *
         * <code>LOGIN_REQ = 3;</code>
         */
        public static final int LOGIN_REQ_VALUE = 3;
        /**
         * <pre>
         *握手响应消息
         * </pre>
         *
         * <code>LOGIN_RESP = 4;</code>
         */
        public static final int LOGIN_RESP_VALUE = 4;
        /**
         * <pre>
         *心跳请求消息
         * </pre>
         *
         * <code>PING = 5;</code>
         */
        public static final int PING_VALUE = 5;
        /**
         * <pre>
         *心跳响应消息
         * </pre>
         *
         * <code>PONG = 6;</code>
         */
        public static final int PONG_VALUE = 6;


        public final int getNumber() {
          if (this == UNRECOGNIZED) {
            throw new IllegalArgumentException(
                "Can't get the number of an unknown enum value.");
          }
          return value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @Deprecated
        public static MessgeType valueOf(int value) {
          return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static MessgeType forNumber(int value) {
          switch (value) {
            case 0: return SERVICE_REQ;
            case 1: return SERVICE_RESP;
            case 2: return ONE_WAY;
            case 3: return LOGIN_REQ;
            case 4: return LOGIN_RESP;
            case 5: return PING;
            case 6: return PONG;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<MessgeType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            MessgeType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<MessgeType>() {
                public MessgeType findValueByNumber(int number) {
                  return MessgeType.forNumber(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          if (this == UNRECOGNIZED) {
            throw new IllegalStateException(
                "Can't get the descriptor of an unrecognized enum value.");
          }
          return getDescriptor().getValues().get(ordinal());
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return CustomHeader.getDescriptor().getEnumTypes().get(0);
        }

        private static final MessgeType[] VALUES = values();

        public static MessgeType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          if (desc.getIndex() == -1) {
            return UNRECOGNIZED;
          }
          return VALUES[desc.getIndex()];
        }

        private final int value;

        private MessgeType(int value) {
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:CustomMessage.CustomHeader.MessgeType)
      }

      public static final int CRCCODE_FIELD_NUMBER = 1;
      private int crcCode_;
      /**
       * <code>int32 crcCode = 1;</code>
       * @return The crcCode.
       */
      @Override
      public int getCrcCode() {
        return crcCode_;
      }

      public static final int LENGTH_FIELD_NUMBER = 2;
      private int length_;
      /**
       * <code>int32 length = 2;</code>
       * @return The length.
       */
      @Override
      public int getLength() {
        return length_;
      }

      public static final int SESSIONID_FIELD_NUMBER = 3;
      private long sessionId_;
      /**
       * <code>int64 sessionId = 3;</code>
       * @return The sessionId.
       */
      @Override
      public long getSessionId() {
        return sessionId_;
      }

      public static final int TYPE_FIELD_NUMBER = 4;
      private int type_;
      /**
       * <code>.CustomMessage.CustomHeader.MessgeType type = 4;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.CustomMessage.CustomHeader.MessgeType type = 4;</code>
       * @return The type.
       */
      @Override public MessgeType getType() {
        @SuppressWarnings("deprecation")
        MessgeType result = MessgeType.valueOf(type_);
        return result == null ? MessgeType.UNRECOGNIZED : result;
      }

      public static final int PRIORITY_FIELD_NUMBER = 5;
      private int priority_;
      /**
       * <code>int32 priority = 5;</code>
       * @return The priority.
       */
      @Override
      public int getPriority() {
        return priority_;
      }

      public static final int ATTACHMENT_FIELD_NUMBER = 6;
      private static final class AttachmentDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<
            String, com.google.protobuf.Any> defaultEntry =
                com.google.protobuf.MapEntry
                .<String, com.google.protobuf.Any>newDefaultInstance(
                    CustomMessageProto.internal_static_CustomMessage_CustomHeader_AttachmentEntry_descriptor,
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "",
                    com.google.protobuf.WireFormat.FieldType.MESSAGE,
                    com.google.protobuf.Any.getDefaultInstance());
      }
      private com.google.protobuf.MapField<
          String, com.google.protobuf.Any> attachment_;
      private com.google.protobuf.MapField<String, com.google.protobuf.Any>
      internalGetAttachment() {
        if (attachment_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AttachmentDefaultEntryHolder.defaultEntry);
        }
        return attachment_;
      }

      public int getAttachmentCount() {
        return internalGetAttachment().getMap().size();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */

      @Override
      public boolean containsAttachment(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetAttachment().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAttachmentMap()} instead.
       */
      @Override
      @Deprecated
      public java.util.Map<String, com.google.protobuf.Any> getAttachment() {
        return getAttachmentMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */
      @Override

      public java.util.Map<String, com.google.protobuf.Any> getAttachmentMap() {
        return internalGetAttachment().getMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */
      @Override

      public com.google.protobuf.Any getAttachmentOrDefault(
          String key,
          com.google.protobuf.Any defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, com.google.protobuf.Any> map =
            internalGetAttachment().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */
      @Override

      public com.google.protobuf.Any getAttachmentOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, com.google.protobuf.Any> map =
            internalGetAttachment().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (crcCode_ != 0) {
          output.writeInt32(1, crcCode_);
        }
        if (length_ != 0) {
          output.writeInt32(2, length_);
        }
        if (sessionId_ != 0L) {
          output.writeInt64(3, sessionId_);
        }
        if (type_ != MessgeType.SERVICE_REQ.getNumber()) {
          output.writeEnum(4, type_);
        }
        if (priority_ != 0) {
          output.writeInt32(5, priority_);
        }
        com.google.protobuf.GeneratedMessageV3
          .serializeStringMapTo(
            output,
            internalGetAttachment(),
            AttachmentDefaultEntryHolder.defaultEntry,
            6);
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (crcCode_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, crcCode_);
        }
        if (length_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, length_);
        }
        if (sessionId_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, sessionId_);
        }
        if (type_ != MessgeType.SERVICE_REQ.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(4, type_);
        }
        if (priority_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, priority_);
        }
        for (java.util.Map.Entry<String, com.google.protobuf.Any> entry
             : internalGetAttachment().getMap().entrySet()) {
          com.google.protobuf.MapEntry<String, com.google.protobuf.Any>
          attachment__ = AttachmentDefaultEntryHolder.defaultEntry.newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
          size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(6, attachment__);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof CustomHeader)) {
          return super.equals(obj);
        }
        CustomHeader other = (CustomHeader) obj;

        if (getCrcCode()
            != other.getCrcCode()) return false;
        if (getLength()
            != other.getLength()) return false;
        if (getSessionId()
            != other.getSessionId()) return false;
        if (type_ != other.type_) return false;
        if (getPriority()
            != other.getPriority()) return false;
        if (!internalGetAttachment().equals(
            other.internalGetAttachment())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CRCCODE_FIELD_NUMBER;
        hash = (53 * hash) + getCrcCode();
        hash = (37 * hash) + LENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getLength();
        hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSessionId());
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
        hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
        hash = (53 * hash) + getPriority();
        if (!internalGetAttachment().getMap().isEmpty()) {
          hash = (37 * hash) + ATTACHMENT_FIELD_NUMBER;
          hash = (53 * hash) + internalGetAttachment().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static CustomHeader parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CustomHeader parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CustomHeader parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CustomHeader parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CustomHeader parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static CustomHeader parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static CustomHeader parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static CustomHeader parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static CustomHeader parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static CustomHeader parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static CustomHeader parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static CustomHeader parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(CustomHeader prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CustomMessage.CustomHeader}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CustomMessage.CustomHeader)
          CustomHeaderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return CustomMessageProto.internal_static_CustomMessage_CustomHeader_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
            int number) {
          switch (number) {
            case 6:
              return internalGetAttachment();
            default:
              throw new RuntimeException(
                  "Invalid map field number: " + number);
          }
        }
        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMutableMapField(
            int number) {
          switch (number) {
            case 6:
              return internalGetMutableAttachment();
            default:
              throw new RuntimeException(
                  "Invalid map field number: " + number);
          }
        }
        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return CustomMessageProto.internal_static_CustomMessage_CustomHeader_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  CustomHeader.class, Builder.class);
        }

        // Construct using fun.codenow.netty.privateprotocol.protobuf.CustomMessageProto.CustomMessage.CustomHeader.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          crcCode_ = 0;

          length_ = 0;

          sessionId_ = 0L;

          type_ = 0;

          priority_ = 0;

          internalGetMutableAttachment().clear();
          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return CustomMessageProto.internal_static_CustomMessage_CustomHeader_descriptor;
        }

        @Override
        public CustomHeader getDefaultInstanceForType() {
          return CustomHeader.getDefaultInstance();
        }

        @Override
        public CustomHeader build() {
          CustomHeader result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public CustomHeader buildPartial() {
          CustomHeader result = new CustomHeader(this);
          int from_bitField0_ = bitField0_;
          result.crcCode_ = crcCode_;
          result.length_ = length_;
          result.sessionId_ = sessionId_;
          result.type_ = type_;
          result.priority_ = priority_;
          result.attachment_ = internalGetAttachment();
          result.attachment_.makeImmutable();
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof CustomHeader) {
            return mergeFrom((CustomHeader)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(CustomHeader other) {
          if (other == CustomHeader.getDefaultInstance()) return this;
          if (other.getCrcCode() != 0) {
            setCrcCode(other.getCrcCode());
          }
          if (other.getLength() != 0) {
            setLength(other.getLength());
          }
          if (other.getSessionId() != 0L) {
            setSessionId(other.getSessionId());
          }
          if (other.type_ != 0) {
            setTypeValue(other.getTypeValue());
          }
          if (other.getPriority() != 0) {
            setPriority(other.getPriority());
          }
          internalGetMutableAttachment().mergeFrom(
              other.internalGetAttachment());
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          CustomHeader parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (CustomHeader) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int crcCode_ ;
        /**
         * <code>int32 crcCode = 1;</code>
         * @return The crcCode.
         */
        @Override
        public int getCrcCode() {
          return crcCode_;
        }
        /**
         * <code>int32 crcCode = 1;</code>
         * @param value The crcCode to set.
         * @return This builder for chaining.
         */
        public Builder setCrcCode(int value) {

          crcCode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 crcCode = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearCrcCode() {

          crcCode_ = 0;
          onChanged();
          return this;
        }

        private int length_ ;
        /**
         * <code>int32 length = 2;</code>
         * @return The length.
         */
        @Override
        public int getLength() {
          return length_;
        }
        /**
         * <code>int32 length = 2;</code>
         * @param value The length to set.
         * @return This builder for chaining.
         */
        public Builder setLength(int value) {

          length_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 length = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearLength() {

          length_ = 0;
          onChanged();
          return this;
        }

        private long sessionId_ ;
        /**
         * <code>int64 sessionId = 3;</code>
         * @return The sessionId.
         */
        @Override
        public long getSessionId() {
          return sessionId_;
        }
        /**
         * <code>int64 sessionId = 3;</code>
         * @param value The sessionId to set.
         * @return This builder for chaining.
         */
        public Builder setSessionId(long value) {

          sessionId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 sessionId = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearSessionId() {

          sessionId_ = 0L;
          onChanged();
          return this;
        }

        private int type_ = 0;
        /**
         * <code>.CustomMessage.CustomHeader.MessgeType type = 4;</code>
         * @return The enum numeric value on the wire for type.
         */
        @Override public int getTypeValue() {
          return type_;
        }
        /**
         * <code>.CustomMessage.CustomHeader.MessgeType type = 4;</code>
         * @param value The enum numeric value on the wire for type to set.
         * @return This builder for chaining.
         */
        public Builder setTypeValue(int value) {

          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.CustomMessage.CustomHeader.MessgeType type = 4;</code>
         * @return The type.
         */
        @Override
        public MessgeType getType() {
          @SuppressWarnings("deprecation")
          MessgeType result = MessgeType.valueOf(type_);
          return result == null ? MessgeType.UNRECOGNIZED : result;
        }
        /**
         * <code>.CustomMessage.CustomHeader.MessgeType type = 4;</code>
         * @param value The type to set.
         * @return This builder for chaining.
         */
        public Builder setType(MessgeType value) {
          if (value == null) {
            throw new NullPointerException();
          }

          type_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.CustomMessage.CustomHeader.MessgeType type = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearType() {

          type_ = 0;
          onChanged();
          return this;
        }

        private int priority_ ;
        /**
         * <code>int32 priority = 5;</code>
         * @return The priority.
         */
        @Override
        public int getPriority() {
          return priority_;
        }
        /**
         * <code>int32 priority = 5;</code>
         * @param value The priority to set.
         * @return This builder for chaining.
         */
        public Builder setPriority(int value) {

          priority_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 priority = 5;</code>
         * @return This builder for chaining.
         */
        public Builder clearPriority() {

          priority_ = 0;
          onChanged();
          return this;
        }

        private com.google.protobuf.MapField<
            String, com.google.protobuf.Any> attachment_;
        private com.google.protobuf.MapField<String, com.google.protobuf.Any>
        internalGetAttachment() {
          if (attachment_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                AttachmentDefaultEntryHolder.defaultEntry);
          }
          return attachment_;
        }
        private com.google.protobuf.MapField<String, com.google.protobuf.Any>
        internalGetMutableAttachment() {
          onChanged();;
          if (attachment_ == null) {
            attachment_ = com.google.protobuf.MapField.newMapField(
                AttachmentDefaultEntryHolder.defaultEntry);
          }
          if (!attachment_.isMutable()) {
            attachment_ = attachment_.copy();
          }
          return attachment_;
        }

        public int getAttachmentCount() {
          return internalGetAttachment().getMap().size();
        }
        /**
         * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
         */

        @Override
        public boolean containsAttachment(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          return internalGetAttachment().getMap().containsKey(key);
        }
        /**
         * Use {@link #getAttachmentMap()} instead.
         */
        @Override
        @Deprecated
        public java.util.Map<String, com.google.protobuf.Any> getAttachment() {
          return getAttachmentMap();
        }
        /**
         * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
         */
        @Override

        public java.util.Map<String, com.google.protobuf.Any> getAttachmentMap() {
          return internalGetAttachment().getMap();
        }
        /**
         * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
         */
        @Override

        public com.google.protobuf.Any getAttachmentOrDefault(
            String key,
            com.google.protobuf.Any defaultValue) {
          if (key == null) { throw new NullPointerException(); }
          java.util.Map<String, com.google.protobuf.Any> map =
              internalGetAttachment().getMap();
          return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
         */
        @Override

        public com.google.protobuf.Any getAttachmentOrThrow(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          java.util.Map<String, com.google.protobuf.Any> map =
              internalGetAttachment().getMap();
          if (!map.containsKey(key)) {
            throw new IllegalArgumentException();
          }
          return map.get(key);
        }

        public Builder clearAttachment() {
          internalGetMutableAttachment().getMutableMap()
              .clear();
          return this;
        }
        /**
         * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
         */

        public Builder removeAttachment(
            String key) {
          if (key == null) { throw new NullPointerException(); }
          internalGetMutableAttachment().getMutableMap()
              .remove(key);
          return this;
        }
        /**
         * Use alternate mutation accessors instead.
         */
        @Deprecated
        public java.util.Map<String, com.google.protobuf.Any>
        getMutableAttachment() {
          return internalGetMutableAttachment().getMutableMap();
        }
        /**
         * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
         */
        public Builder putAttachment(
            String key,
            com.google.protobuf.Any value) {
          if (key == null) { throw new NullPointerException(); }
          if (value == null) { throw new NullPointerException(); }
          internalGetMutableAttachment().getMutableMap()
              .put(key, value);
          return this;
        }
        /**
         * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
         */

        public Builder putAllAttachment(
            java.util.Map<String, com.google.protobuf.Any> values) {
          internalGetMutableAttachment().getMutableMap()
              .putAll(values);
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:CustomMessage.CustomHeader)
      }

      // @@protoc_insertion_point(class_scope:CustomMessage.CustomHeader)
      private static final CustomHeader DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new CustomHeader();
      }

      public static CustomHeader getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<CustomHeader>
          PARSER = new com.google.protobuf.AbstractParser<CustomHeader>() {
        @Override
        public CustomHeader parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CustomHeader(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<CustomHeader> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<CustomHeader> getParserForType() {
        return PARSER;
      }

      @Override
      public CustomHeader getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private CustomHeader header_;
    /**
     * <code>.CustomMessage.CustomHeader header = 1;</code>
     * @return Whether the header field is set.
     */
    @Override
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.CustomMessage.CustomHeader header = 1;</code>
     * @return The header.
     */
    @Override
    public CustomHeader getHeader() {
      return header_ == null ? CustomHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.CustomMessage.CustomHeader header = 1;</code>
     */
    @Override
    public CustomHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.Any body_;
    /**
     * <code>.google.protobuf.Any body = 2;</code>
     * @return Whether the body field is set.
     */
    @Override
    public boolean hasBody() {
      return body_ != null;
    }
    /**
     * <code>.google.protobuf.Any body = 2;</code>
     * @return The body.
     */
    @Override
    public com.google.protobuf.Any getBody() {
      return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
    }
    /**
     * <code>.google.protobuf.Any body = 2;</code>
     */
    @Override
    public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
      return getBody();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (body_ != null) {
        output.writeMessage(2, getBody());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (body_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBody());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CustomMessage)) {
        return super.equals(obj);
      }
      CustomMessage other = (CustomMessage) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CustomMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CustomMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CustomMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CustomMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CustomMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CustomMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CustomMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CustomMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CustomMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CustomMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CustomMessage)
        CustomMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CustomMessageProto.internal_static_CustomMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CustomMessageProto.internal_static_CustomMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CustomMessage.class, Builder.class);
      }

      // Construct using fun.codenow.netty.privateprotocol.protobuf.CustomMessageProto.CustomMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (bodyBuilder_ == null) {
          body_ = null;
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CustomMessageProto.internal_static_CustomMessage_descriptor;
      }

      @Override
      public CustomMessage getDefaultInstanceForType() {
        return CustomMessage.getDefaultInstance();
      }

      @Override
      public CustomMessage build() {
        CustomMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CustomMessage buildPartial() {
        CustomMessage result = new CustomMessage(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CustomMessage) {
          return mergeFrom((CustomMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CustomMessage other) {
        if (other == CustomMessage.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CustomMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CustomMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private CustomHeader header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          CustomHeader, CustomHeader.Builder, CustomHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.CustomMessage.CustomHeader header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.CustomMessage.CustomHeader header = 1;</code>
       * @return The header.
       */
      public CustomHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? CustomHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.CustomMessage.CustomHeader header = 1;</code>
       */
      public Builder setHeader(CustomHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CustomMessage.CustomHeader header = 1;</code>
       */
      public Builder setHeader(
          CustomHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CustomMessage.CustomHeader header = 1;</code>
       */
      public Builder mergeHeader(CustomHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              CustomHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CustomMessage.CustomHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CustomMessage.CustomHeader header = 1;</code>
       */
      public CustomHeader.Builder getHeaderBuilder() {

        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.CustomMessage.CustomHeader header = 1;</code>
       */
      public CustomHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              CustomHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.CustomMessage.CustomHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          CustomHeader, CustomHeader.Builder, CustomHeaderOrBuilder>
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              CustomHeader, CustomHeader.Builder, CustomHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.google.protobuf.Any body_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bodyBuilder_;
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       * @return Whether the body field is set.
       */
      public boolean hasBody() {
        return bodyBuilder_ != null || body_ != null;
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       * @return The body.
       */
      public com.google.protobuf.Any getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder setBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder setBody(
          com.google.protobuf.Any.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder mergeBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (body_ != null) {
            body_ =
              com.google.protobuf.Any.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = null;
          onChanged();
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public com.google.protobuf.Any.Builder getBodyBuilder() {

        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : body_;
        }
      }
      /**
       * <code>.google.protobuf.Any body = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CustomMessage)
    }

    // @@protoc_insertion_point(class_scope:CustomMessage)
    private static final CustomMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CustomMessage();
    }

    public static CustomMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CustomMessage>
        PARSER = new com.google.protobuf.AbstractParser<CustomMessage>() {
      @Override
      public CustomMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CustomMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CustomMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CustomMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public CustomMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomMessage_CustomHeader_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomMessage_CustomHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CustomMessage_CustomHeader_AttachmentEntry_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CustomMessage_CustomHeader_AttachmentEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023CustomMessage.proto\032\031google/protobuf/a" +
      "ny.proto\"\350\003\n\rCustomMessage\022+\n\006header\030\001 \001" +
      "(\0132\033.CustomMessage.CustomHeader\022\"\n\004body\030" +
      "\002 \001(\0132\024.google.protobuf.Any\032\205\003\n\014CustomHe" +
      "ader\022\017\n\007crcCode\030\001 \001(\005\022\016\n\006length\030\002 \001(\005\022\021\n" +
      "\tsessionId\030\003 \001(\003\0224\n\004type\030\004 \001(\0162&.CustomM" +
      "essage.CustomHeader.MessgeType\022\020\n\010priori" +
      "ty\030\005 \001(\005\022?\n\nattachment\030\006 \003(\0132+.CustomMes" +
      "sage.CustomHeader.AttachmentEntry\032G\n\017Att" +
      "achmentEntry\022\013\n\003key\030\001 \001(\t\022#\n\005value\030\002 \001(\013" +
      "2\024.google.protobuf.Any:\0028\001\"o\n\nMessgeType" +
      "\022\017\n\013SERVICE_REQ\020\000\022\020\n\014SERVICE_RESP\020\001\022\013\n\007O" +
      "NE_WAY\020\002\022\r\n\tLOGIN_REQ\020\003\022\016\n\nLOGIN_RESP\020\004\022" +
      "\010\n\004PING\020\005\022\010\n\004PONG\020\006B@\n*fun.codenow.netty" +
      ".privateprotocol.protobufB\022CustomMessage" +
      "Protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_CustomMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CustomMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomMessage_descriptor,
        new String[] { "Header", "Body", });
    internal_static_CustomMessage_CustomHeader_descriptor =
      internal_static_CustomMessage_descriptor.getNestedTypes().get(0);
    internal_static_CustomMessage_CustomHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomMessage_CustomHeader_descriptor,
        new String[] { "CrcCode", "Length", "SessionId", "Type", "Priority", "Attachment", });
    internal_static_CustomMessage_CustomHeader_AttachmentEntry_descriptor =
      internal_static_CustomMessage_CustomHeader_descriptor.getNestedTypes().get(0);
    internal_static_CustomMessage_CustomHeader_AttachmentEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CustomMessage_CustomHeader_AttachmentEntry_descriptor,
        new String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
